name:                seitz-symbol
version:             0.1.0.0
github:              "narumij/seitz-symbol"
license:             MIT
author:              "Jun Narumi"
maintainer:          "narumij@gmail.com"
copyright:           "Jun Narumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/narumij/seitz-symbol#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- matrix
- matrix-as-xyz

library:
  source-dirs: src

tests:
  seitz-symbol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seitz-symbol
